[project]
name = "ds-salary-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matin Mohammadi", email = "matinmohammadi031@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://mirror-pypi.runflare.com/simple"
default = true

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
